### ISSUE TITLE
Boundary check for pressure and p_tp.

### ISSUE THREAD

**Issue by peterg1t** [jrkerns/pylinac#415] opened 2021-12-08 22:45 UTC
**Describe the bug**
Pressure value was not in the allowed range (90,115)

**To Reproduce**
1. Run the test script with 89 kPa as a value for variable PRESS

**Expected behavior**
Pressure at our center hovers below the 90 kPa mark. This results in Ptp corrections larger than 1.1. This should be allowed as well (currently restricted to 0.9-1.1 range)

**Screenshots**
![image](https://user-images.githubusercontent.com/8771255/145303105-30ea916f-801c-4e88-8b72-7cb9c3b5c6d2.png)

**Additional context**

**Comment by jrkerns** [comment] 2021-12-09 17:10
Duplicate of #353 . See here for how to change it: https://pylinac.readthedocs.io/en/latest/calibration_docs.html#changing-a-bound

**Closed** 2021-12-09 17:36 UTC
